Repository ngchrbn/GOFO-Booking, pull requests merged in 2021-06, with the labels that each got.

#2 Changed Structure
  src/GOFO/System/GoFo.java
  src/Main.java
Labels: enhancement

#3 Implemented UI class
  src/GOFO/System/GoFo.java
  src/GOFO/UI/AdministratorUI.java
  src/GOFO/UI/EwalletUI.java
  src/GOFO/UI/PlayerUI.java
  src/GOFO/UI/PlaygroundOwnerUI.java
  src/GOFO/UI/UI.java
  src/GOFO/User/Player.java
  src/GOFO/User/PlaygroundOwner.java
  src/GOFO/User/User.java
  src/GOFO/Utilities/Address.java
  src/Main.java
Labels: documentation, enhancement

#6 Implement-Utilities
  src/GOFO/Utilities/Address.java
  src/GOFO/Utilities/Ewallet.java
  src/GOFO/Utilities/Playground.java
  src/GOFO/Utilities/Team.java
  src/GOFO/Utilities/TimeSlot.java
Labels: enhancement

#7 Implemented Administrator.java
  src/GOFO/User/Administrator.java
Labels: enhancement

#10 Added Ewallet object
  src/GOFO/System/GoFo.java
  src/GOFO/UI/UI.java
  src/GOFO/User/Player.java
  src/GOFO/User/PlaygroundOwner.java
  src/GOFO/User/User.java
  src/GOFO/Utilities/Ewallet.java
Labels: documentation

#11 Add playground
  src/GOFO/System/GoFo.java
  src/GOFO/UI/AdministratorUI.java
  src/GOFO/UI/PlaygroundOwnerUI.java
  src/GOFO/UI/UI.java
  src/GOFO/User/PlaygroundOwner.java
  src/GOFO/User/User.java
  src/GOFO/Utilities/Playground.java
Labels: enhancement

#12 Implemented book-playground
  src/GOFO/System/GoFo.java
  src/GOFO/UI/PlayerUI.java
  src/GOFO/Utilities/Ewallet.java
  src/GOFO/Utilities/TimeSlot.java
Labels: enhancement

#14 View playground info
  src/GOFO/System/GoFo.java
  src/GOFO/UI/PlayerUI.java
Labels: enhancement

#16 Update get playgrounds
  src/GOFO/System/GoFo.java
  src/GOFO/UI/AdministratorUI.java
  src/GOFO/UI/PlaygroundOwnerUI.java
Labels: enhancement

#17 Added checking of Playground State.
  src/GOFO/System/GoFo.java
  src/GOFO/UI/PlayerUI.java
Labels: bug

#22 Added System package documentation
  src/GOFO/System/GoFo.java
Labels: documentation

#23 Documented UI package.
  src/GOFO/UI/AdministratorUI.java
  src/GOFO/UI/EwalletUI.java
  src/GOFO/UI/PlayerUI.java
  src/GOFO/UI/PlaygroundOwnerUI.java
  src/GOFO/UI/UI.java
Labels: documentation

#24 Documented User package.
  src/GOFO/User/Administrator.java
  src/GOFO/User/Player.java
  src/GOFO/User/PlaygroundOwner.java
  src/GOFO/User/User.java
Labels: documentation

#25 Documented Utilities package
  src/GOFO/Utilities/Address.java
  src/GOFO/Utilities/Ewallet.java
  src/GOFO/Utilities/Playground.java
  src/GOFO/Utilities/Team.java
  src/GOFO/Utilities/TimeSlot.java
Labels: documentation

#26 Updated book a playground function.
  src/GOFO/System/GoFo.java
  src/GOFO/UI/AdministratorUI.java
  src/GOFO/UI/PlayerUI.java
  src/GOFO/UI/PlaygroundOwnerUI.java
Labels: bug, enhancement, implementation

#27 Added possibility to send an invitation after booking
  src/GOFO/System/GoFo.java
  src/GOFO/UI/PlayerUI.java
  src/GOFO/UI/UI.java
  src/GOFO/User/Player.java
  src/GOFO/Utilities/Address.java
  src/GOFO/Utilities/Team.java
  src/GOFO/Utilities/TimeSlot.java
Labels: enhancement
